# Generated by Django 3.0.5 on 2020-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_hello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='name',
            field=models.CharField(help_text='this is the size of shirt', max_length=100, verbose_name='custom name'),
        ),
    ]
