# Generated by Django 3.0.5 on 2020-09-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20200907_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Personsssss'},
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='is_legal',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
